Controllers/CompanyController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using TestUkrposhta.BusinessService;
using TestUkrposhta.Models;

namespace TestUkrposhta.Controllers
{
    public class CompanyController : Controller
    {
        private readonly IMapper _mapper;
        private readonly ICompanyBusinessService _companyBS;

        public CompanyController(IMapper mapper, ICompanyBusinessService companyBS)
        {
            _mapper = mapper;
            _companyBS = companyBS;
        }

        public async Task<IActionResult> Index()
        {
            var companyDTO = await _companyBS.GetCompanyAsync();
            var companyModel = _mapper.Map<CompanyReadModel>(companyDTO);

            return View(companyModel);
        }

        [HttpGet("Company/{companyID}")]
        public async Task<IActionResult> GetCompanyInfo(int? companyID = null)
        {
            var companyDTO = await _companyBS.GetCompanyAsync(companyID);
            var companyModel = _mapper.Map<CompanyReadModel>(companyDTO);

            return View(companyModel);
        }
    }
}

Controllers/EmployeeController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using TestUkrposhta.BusinessService;
using TestUkrposhta.DTOs;
using TestUkrposhta.Models;

namespace TestUkrposhta.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IEmployeeBusinessService _employeeBS;
        private readonly IPositionBusinessService _positionBS;
        private readonly IDepartamentBusinessService _departamentBS;

        public EmployeeController(IMapper mapper, IEmployeeBusinessService employeeBS, IPositionBusinessService positionBS, IDepartamentBusinessService departamentBS)
        {
            _mapper = mapper;
            _employeeBS = employeeBS;
            _positionBS = positionBS;
            _departamentBS = departamentBS;
        }

        public async Task<IActionResult> Index()
        {
            // Getting positions and departaments for dropdown lists for page
            var positionDTOs = await _positionBS.GetPositionsAsync();
            var departamentDTOs = await _departamentBS.GetDepartamentsAsync();

            var positionModels = _mapper.Map<IList<PositionReadModel>>(positionDTOs);
            var departamentModels = _mapper.Map<IList<DepartamentReadModel>>(departamentDTOs);

            var model = new EmployeeFilterDropDownListsModel(positionModels, departamentModels);

            // Render Page
            return View(model);
        }

        [HttpGet("GetEmployeesTableView")]
        public async Task<IActionResult> EmployeesTable()
        {
            try
            {
                // Getting employees
                var employeeDTOs = await _employeeBS.GetAllAsync();
                var employeeModels = _mapper.Map<IEnumerable<EmployeeReadModel>>(employeeDTOs);

                var model = new EmployeeTableModel
                {
                    Employees = employeeModels,
                };

                // Render Table
                return View(model);
            }
            catch (Exception ex)
            {
                var model = new EmployeeTableModel
                {
                    Error = $"Error in GetEmployeesTableView get method: {ex.Message}",
                };

                // Render Table
                return View(model);
            }
        }

        [HttpPost("GetEmployeesTableView")]
        public async Task<IActionResult> EmployeesTableWithFilter()
        {
            try
            {
                // Getting filter
                var filterModel = await Request.ReadFromJsonAsync<EmployeeFilterModel>();
                var filterDTO = _mapper.Map<EmployeeFilter>(filterModel);

                // Getting employees
                var employeeDTOs = await _employeeBS.GetListByFilterAsync(filterDTO);
                var employeeModels = _mapper.Map<IEnumerable<EmployeeReadModel>>(employeeDTOs);

                var model = new EmployeeTableModel
                {
                    Employees = employeeModels,
                };

                // Render Table
                return View("EmployeesTable", model);
            }
            catch (Exception ex)
            {
                var model = new EmployeeTableModel
                {
                    Error = $"Error in GetEmployeesTableView post method: {ex.Message}",
                };

                // Render Table
                return View("EmployeesTable", model);
            }
        }

        [HttpGet("GetEmployee/{employeeID}")]
        public async Task<IActionResult> GetEmployee(int employeeID)
        {
            try
            {
                var employeeDTO = await _employeeBS.GetEmployeeAsync(employeeID) ?? throw new Exception("Employee not found in db");
                var employeeModel = _mapper.Map<EmployeeUpdateModel>(employeeDTO);

                return Ok(employeeModel);
            }
            catch (Exception ex)
            {
                return Ok(new { Error = $"Error in GetEmployee/{employeeID}: {ex.Message}" });
            }
        }

        [HttpPut("SaveEmployee/{employeeID}")]
        public async Task<IActionResult> SaveEmployee(int employeeID)
        {
            try
            {
                var employeeModel = await Request.ReadFromJsonAsync<EmployeeUpdateModel>();
                var employeeDTO = _mapper.Map<Employee>(employeeModel);

                await _employeeBS.UpdateEmployeeAsync(employeeDTO);

                // Nothing to return
                return Ok(new { });
            }
            catch (Exception ex)
            {
                return Ok(new { Error = $"Error in SaveEmployee/{employeeID}: {ex.Message}" });
            }
        }
    }
}

Controllers/SalaryReportsController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using TestUkrposhta.BusinessService;
using TestUkrposhta.DTOs;
using TestUkrposhta.Models;
using TestUkrposhta.Tools;

namespace TestUkrposhta.Controllers
{
    public class SalaryReportsController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IEmployeeBusinessService _employeeBS;
        private readonly IPositionBusinessService _positionBS;
        private readonly IDepartamentBusinessService _departamentBS;

        public SalaryReportsController(IMapper mapper, IEmployeeBusinessService employeeBS, IPositionBusinessService positionBS, IDepartamentBusinessService departamentBS)
        {
            _mapper = mapper;
            _employeeBS = employeeBS;
            _positionBS = positionBS;
            _departamentBS = departamentBS;
        }

        public async Task<IActionResult> Index()
        {
            // Getting positions and departaments for dropdown lists for page
            var positionDTOs = await _positionBS.GetPositionsAsync();
            var departamentDTOs = await _departamentBS.GetDepartamentsAsync();

            var positionModels = _mapper.Map<IList<PositionReadModel>>(positionDTOs);
            var departamentModels = _mapper.Map<IList<DepartamentReadModel>>(departamentDTOs);

            var model = new EmployeeFilterDropDownListsModel(positionModels, departamentModels);

            // Render Page
            return View(model);
        }

        [HttpGet("GetSalaryReportsTableView")]
        public async Task<IActionResult> SalaryReportsTable()
        {
            try
            {
                // Getting employees
                var employeeDTOs = await _employeeBS.GetSalaryReportsAsync();
                var employeeModels = _mapper.Map<IEnumerable<SalaryReportsReadModel>>(employeeDTOs);

                var model = new SalaryReportsTableModel
                {
                    Employees = employeeModels,
                };

                // Render Table
                return View(model);
            }
            catch (Exception ex)
            {
                var model = new SalaryReportsTableModel
                {
                    Error = $"Error in GetSalaryReportsTableView get method: {ex.Message}",
                };

                // Render Table
                return View(model);
            }
        }

        [HttpPost("GetSalaryReportsTableView")]
        public async Task<IActionResult> SalaryReportsTableWithFilter()
        {
            try
            {
                // Getting filter
                var filterModel = await Request.ReadFromJsonAsync<SalaryReportsFilterModel>();
                var filterDTO = _mapper.Map<SalaryReportsFilter>(filterModel);

                // Getting employees
                var employeeDTOs = await _employeeBS.GetSalaryReportsAsync(filterDTO);
                var employeeModels = _mapper.Map<IEnumerable<SalaryReportsReadModel>>(employeeDTOs);

                var model = new SalaryReportsTableModel
                {
                    Employees = employeeModels,
                };

                // Render Table
                return View("SalaryReportsTable", model);
            }
            catch (Exception ex)
            {
                var model = new SalaryReportsTableModel
                {
                    Error = $"Error in GetSalaryReportsTableView post method: {ex.Message}",
                };

                // Render Table
                return View("SalaryReportsTable", model);
            }
        }


        [HttpPost("GetSalaryReportsTxtFile")]
        public async Task<IActionResult> GetSalaryReportsTxtFile()
        {
            try
            {
                // Getting filter
                var filterModel = await Request.ReadFromJsonAsync<SalaryReportsFilterModel>();
                var filterDTO = _mapper.Map<SalaryReportsFilter>(filterModel);

                // Getting employees
                var employeeDTOs = await _employeeBS.GetSalaryReportsAsync(filterDTO);
                var employeeModels = _mapper.Map<IEnumerable<SalaryReportsReadModel>>(employeeDTOs);

                var table = TxtGenerator.GetSalaryReportsTable(employeeModels, filterModel);

                // Sending file
                return File(table,
                 "text/plain",
                 "SalaryReport.txt");
            }
            catch (Exception ex)
            {
                // Render Table
                return Ok(new { Error = $"Error in GetSalaryReportsTxtFile: {ex.Message}" });
            }
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Test Task Ukrposhta</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/jquery-ui/jquery-ui.min.css" />
    <link rel="stylesheet" href="~/lib/jquery-ui/jquery-ui.structure.min.css" />
    <link rel="stylesheet" href="~/lib/jquery-ui/jquery-ui.theme.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TestUkrposhta.styles.css" asp-append-version="true" />
</head>
<body>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-ui/jquery-ui.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Company" asp-action="Index">Test Task Ukrposhta</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Company" asp-action="Index">Company Info</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employees</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SalaryReports" asp-action="Index">Salary Reports</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - TestUkrposhta - Egor Podvalkov
        </div>
    </footer>
</body>
</html>